---
title: Workshop Python Image Analysis
jupyter: python3
---

*Martijn Wehrens, September 2025*

**Estimated time:** 120 mins exercises

## Chapter 5: Combining building blocks into a pipeline


To recap, remember we have seen:

- Image **thresholding** creates a **mask**
    - This can be **labeled**
    - And **regionprops** can be determined.
- We can **filter** the image (using labeled image or properties)
- We can also *apply* morphology operations
    - **transformations**
    - **blurring**
    - **edge detection**
    - and more
- We can combine these operations
- We can combine images using numpy operations, 
    - **np.logical_and**, np.logical_or, np.isin, etc..
- There are more specialized algorithms that can do similar things
    - Explore documentation/materials at:
        - Scikit documentation: https://scikit-image.org/docs/stable/api/skimage.morphology.html
        - Scikit tutorials: https://scikit-image.org/docs/stable/auto_examples/index.html#morphology
        - Scipy documentation, e.g. for ndimage: https://docs.scipy.org/doc/scipy/reference/ndimage.html
- We didn't cover advanced topics, and leave those to avid learners, such as:
    - Fourier transform
    - Deconvolution
    - ..    
- Explore more materials at:
    - https://bioimagebook.github.io/
    - https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/intro.html

        

## Automation

To automate a pipeline, the following components are useful:

- Loops
- Functions
    - *Try to code in a modular fashion!*
- Interaction with the filesystem using:
    - `os`, `glob.glob`

*These topics were covered in our previous "Introduction to Python" course.*

## Guided exercises


### Bacterial data

Similarly, design a pipeline such that:

- For all bacterial data, the images get segmented. 
    - It might be convenient to store the segmentation masks somewhere, use `np.savez_compressed` or similar.
- Plot the observed bacterial areas over time.

*Likely your segmentation won't be perfect. In the manuscript, the algorithm was tweaked and segmentation manually corrected and curated. This is an exercise. Don't try to do a perfect job. Use a segmentation function based on chapter 3, and have that loop over the images.*

### Nuclear data

Design a pipeline such that:

- For each frame, the nuclei get segmented.
    - It might be convenient to store the segmentation masks somewhere, use `np.savez_compressed` or similar.
    
- First, for a single image try to do the following:
    - Combine data from the segmentation masks and the other fluorescent channels.
        - In the 2nd (ie channel 1) fluorescent channel, the KTR signal is recorded.
            - You can open the data in FIJI to check.
        - Using your nuclear mask based on the channel 0, calculate the mean signal for each respective nuclei.
- Can you now extract the nuclear KTR signals from nuclei for multiple images? And plot this over time?

- Next, use morphology operations to create a mask that corresponds to a small ring of pixels around the nuclei (ie overlapping with cytoplasm, but excluding the nucleus itself).
    - Now extract the signal from those regions as well.
    - Plot this signal too.
    
- Now for each time t, determine the average nuclear and cytoplasmic signal.
- Plot the nuclear:cytoplasmic ratio over time.
- Can you guess what was done in this experiment?
    


